### ISSUE TITLE
Why are label-for attributes disabled?

### ISSUE THREAD

**Issue by sladiri** [MadRabbit/a-plus-forms#2]
Hi, is there a reason that you disabled the label-for attribute for inputs, or is it just not yet implemented?

**Comment by MadRabbit** [comment]
Hi there,

So, basically, the idea is that A+ form is not supposed to dictate how the final render looks like. There are million ways inputs can be presented in the HTML, it would be impossible to provide a one size fits all solution. Hence the layout that I have by default is just a minimal placeholder, it not supposed to be the final version. Think of it this way, this package is just the data managing core that provides the standard API, everything else supposed to go into extensions.

If you want some styled drop in option, try the boostrap bindings: https://github.com/MadRabbit/a-plus-forms-bootstrap, it has the `LABEL` `for` attribute sorted out.

if you want to build your own here are the docs https://github.com/MadRabbit/a-plus-forms/wiki/Layouts-&-Styling

**Comment by sladiri** [comment]
Thank you for the explanation. I was not sure if this behaviour was intentinoal. I tried the links on the readme from master branch, but they point to 404 pages, so I figured that they were not done yet. I was not aware that there were already wiki-pages.

**Comment by MadRabbit** [comment]
No drama. Any questions, just ask
